spring:
  #redis基础配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis@123
      database: 2
      #redis配置连接池,使用Lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 0



